// Flat ESLint config for the SPA (Q-A9 → D-037: typescript-eslint v8, flat config).
import js from "@eslint/js";
import tseslint from "typescript-eslint";
import tsParser from "@typescript-eslint/parser";
import reactHooks from "eslint-plugin-react-hooks";
import reactRefresh from "eslint-plugin-react-refresh";
import globals from "globals";

export default tseslint.config(
  {
    ignores: [
      "dist/**",
      "node_modules/**",
      "coverage/**",
      // Generated by `make openapi-export` — never hand-edited.
      "src/api/types.ts",
    ],
  },
  js.configs.recommended,
  // Type-aware rules scoped to TS/TSX source files only (non-test).
  // Uses projectService so ESLint has TS type information for no-unsafe-* rules.
  // Per 2026-05-17 strict-linting decision doc §TypeScript/React stack.
  // Test files (*.test.ts/tsx, src/test/**) are excluded here; they get their
  // own config block below with type-aware rules disabled.
  ...tseslint.configs.strictTypeChecked.map((cfg) => ({
    ...cfg,
    files: ["src/**/*.{ts,tsx}"],
    ignores: ["src/**/*.test.{ts,tsx}", "src/test/**/*.{ts,tsx}"],
  })),
  ...tseslint.configs.stylisticTypeChecked.map((cfg) => ({
    ...cfg,
    files: ["src/**/*.{ts,tsx}"],
    ignores: ["src/**/*.test.{ts,tsx}", "src/test/**/*.{ts,tsx}"],
  })),
  {
    // Source files (non-test): strict type-checking via projectService.
    files: ["src/**/*.{ts,tsx}"],
    ignores: ["src/**/*.test.{ts,tsx}", "src/test/**/*.{ts,tsx}"],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: "module",
      globals: {
        ...globals.browser,
        process: "readonly",
      },
      parserOptions: {
        projectService: {
          // tsconfig.app.json excludes test files; allow default project for
          // the three test-helper files that are still TS but aren't test files.
          allowDefaultProject: ["src/test/handlers.ts", "src/test/server.ts", "src/test/setup.ts"],
        },
        tsconfigRootDir: import.meta.dirname,
      },
    },
    plugins: {
      "react-hooks": reactHooks,
      "react-refresh": reactRefresh,
    },
    rules: {
      ...reactHooks.configs.recommended.rules,
      "react-refresh/only-export-components": ["warn", { allowConstantExport: true }],
      "no-unused-vars": "off",
      "@typescript-eslint/no-unused-vars": [
        "warn",
        {
          argsIgnorePattern: "^_",
          varsIgnorePattern: "^_",
          caughtErrorsIgnorePattern: "^_",
        },
      ],
      // Semantic safety rules from strictTypeChecked — kept as errors.
      "@typescript-eslint/no-misused-promises": "error",
      "@typescript-eslint/no-floating-promises": "error",
      "@typescript-eslint/no-unsafe-return": "error",
      "@typescript-eslint/no-unsafe-argument": "error",
      "@typescript-eslint/no-base-to-string": "error",
      "@typescript-eslint/no-invalid-void-type": "error",

      // High-volume rules deferred as warn — mechanical rewrites needed across
      // 219 files; will be converted to errors in incremental follow-on commits.
      // no-confusing-void-expression (328): onClick={() => voidFn()} pattern.
      "@typescript-eslint/no-confusing-void-expression": "warn",
      // restrict-template-expressions (228): ${number} / ${boolean} in templates.
      "@typescript-eslint/restrict-template-expressions": "warn",
      // no-unnecessary-type-assertion (109): our ! non-null guards + noUncheckedIndexedAccess.
      "@typescript-eslint/no-unnecessary-type-assertion": "warn",
      // no-unnecessary-condition (80): some real bugs but too many false positives from
      // the new strict flags for a single commit.
      "@typescript-eslint/no-unnecessary-condition": "warn",
      // require-await (78): async fns lacking await — real but requires refactors.
      "@typescript-eslint/require-await": "warn",
      // no-unsafe-member-access (47): any-typed member access.
      "@typescript-eslint/no-unsafe-member-access": "warn",
      // no-non-null-assertion (28): ! assertions from TS-1a guard narrowing.
      "@typescript-eslint/no-non-null-assertion": "warn",
      // no-empty-function (27): empty mock/stub functions.
      "@typescript-eslint/no-empty-function": "warn",
      // no-unsafe-assignment (15): any-typed assignments.
      "@typescript-eslint/no-unsafe-assignment": "warn",
      // array-type (13): Array<T> vs T[] style — stylisticTypeChecked rule.
      "@typescript-eslint/array-type": "warn",
      // no-unnecessary-type-arguments (6): explicit default generic args.
      "@typescript-eslint/no-unnecessary-type-arguments": "warn",
      // no-unnecessary-type-conversion (5): redundant .toString() etc.
      "@typescript-eslint/no-unnecessary-type-conversion": "warn",
      // prefer-nullish-coalescing (3): || vs ?? — low-value style.
      "@typescript-eslint/prefer-nullish-coalescing": "warn",
      // no-useless-default-assignment (3): default = undefined in destructuring.
      "@typescript-eslint/no-useless-default-assignment": "warn",
      // prefer-regexp-exec (2): .match() vs .exec().
      "@typescript-eslint/prefer-regexp-exec": "warn",
      // no-unsafe-return (2): returning any — already error above, but warn in deferred list.
      // no-inferrable-types (2): const x: string = "y".
      "@typescript-eslint/no-inferrable-types": "warn",
      // consistent-generic-constructors (2): Map<K,V> vs new Map<K,V>().
      "@typescript-eslint/consistent-generic-constructors": "warn",
      // no-explicit-any: error in src/ (test files still "off" via override below).
      "@typescript-eslint/no-explicit-any": "error",
    },
  },
  {
    // Test files: type-aware rules disabled. tsconfig.app.json excludes test
    // files so projectService can't provide type info; we disable project
    // parsing entirely for tests (type-safety rules are all off anyway).
    files: ["src/**/*.test.{ts,tsx}", "src/test/**/*.{ts,tsx}"],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: "module",
      globals: {
        ...globals.browser,
        ...globals.node,
        React: "readonly",
        describe: "readonly",
        it: "readonly",
        test: "readonly",
        expect: "readonly",
        beforeAll: "readonly",
        afterAll: "readonly",
        beforeEach: "readonly",
        afterEach: "readonly",
        vi: "readonly",
        global: "readonly",
        Buffer: "readonly",
        // DOM TypeScript types referenced in test mocks (not in globals.browser)
        RequestInfo: "readonly",
        RequestInit: "readonly",
        FrameRequestCallback: "readonly",
      },
      parser: tsParser,
      parserOptions: {
        // Disable project service for test files — tsconfig.app.json excludes
        // them, and all type-aware rules are disabled in this block anyway.
        projectService: false,
        ecmaFeatures: { jsx: true },
      },
    },
    rules: {
      // Without projectService, the TS parser doesn't enforce unused-vars through
      // @typescript-eslint/no-unused-vars. The base no-unused-vars fires instead;
      // disable it for test files (underscore-prefix is the convention).
      "no-unused-vars": "off",
      "@typescript-eslint/no-explicit-any": "off",
      "@typescript-eslint/no-non-null-assertion": "off",
      // Relax type-safety rules in tests — mocks/spies/stubs are inherently any-typed.
      "@typescript-eslint/no-unsafe-assignment": "off",
      "@typescript-eslint/no-unsafe-member-access": "off",
      "@typescript-eslint/no-unsafe-argument": "off",
      "@typescript-eslint/no-unsafe-return": "off",
      "@typescript-eslint/no-misused-promises": "off",
      "@typescript-eslint/require-await": "off",
      "@typescript-eslint/no-empty-function": "off",
      "@typescript-eslint/no-confusing-void-expression": "off",
      "@typescript-eslint/no-unnecessary-boolean-literal-compare": "off",
    },
  },
);
