"""End-to-end exercise harness against a realistic multi-page project.

Exercises the major UI paths across 8 pages of the ``exercise-fixture``
project, which contains pre-built UserPageEnvelope files with real
block/paragraph/line/word structures (generated by
``scripts/generate_exercise_fixture.py``).

Unlike the conformance tests (``test_driver_contract.py``) and smoke tests
(``test_smoke.py``), this module is intentionally *not* a unit-by-unit
pass/fail matrix — it is a **workflow exercise** that visits real UI paths
in sequence and records failures without aborting.  A single page failure
does not stop the exercise; all results are reported at the end.

Generate the fixture first (idempotent)::

    cd /workspaces/ocr-container/pd-ocr-labeler-spa
    uv run python scripts/generate_exercise_fixture.py

Then run::

    make exercise-real
    # or for headed mode:
    HEADED=1 make exercise-real
    # or directly:
    uv run --group e2e pytest tests/e2e/exercise_real_project.py -v

Spec ref: ``docs/architecture/13-driver-contract.md`` §2 (testid catalogue).
"""

from __future__ import annotations

import shutil
import socket
import threading
import time
from collections.abc import Iterator
from dataclasses import dataclass
from pathlib import Path

import httpx
import pytest
from playwright.sync_api import Page

from pd_ocr_labeler_spa.bootstrap import build_app
from pd_ocr_labeler_spa.settings import Settings

# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------

_EXERCISE_FIXTURE_SRC = Path(__file__).parent / "fixtures" / "projects" / "exercise-fixture"
_PROJECT_ID = "exercise-fixture"
_TOTAL_PAGES = 8


# ---------------------------------------------------------------------------
# Live-server fixture (session-scoped, separate from tiny-fixture server)
# ---------------------------------------------------------------------------


def _pick_free_port() -> int:
    with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:
        s.bind(("127.0.0.1", 0))
        return s.getsockname()[1]


def _spa_built() -> bool:
    static = Path(__file__).resolve().parents[2] / "src" / "pd_ocr_labeler_spa" / "static"
    return (static / "index.html").is_file()


def _wait_until(url: str, timeout: float = 20.0) -> None:
    deadline = time.monotonic() + timeout
    while time.monotonic() < deadline:
        try:
            r = httpx.get(url, timeout=0.5)
            if r.status_code == 200:
                return
        except httpx.HTTPError:
            pass
        time.sleep(0.1)
    raise RuntimeError(f"Server did not become ready at {url!r} within {timeout}s")


@dataclass
class ExerciseServer:
    base_url: str
    settings: Settings
    source_root: Path
    data_root: Path


@pytest.fixture(scope="module")
def exercise_server(tmp_path_factory: pytest.TempPathFactory) -> Iterator[ExerciseServer]:
    """Start a live server seeded with the exercise-fixture project.

    Skips when the SPA bundle is not present or the fixture source is missing.
    Session-scoped at *module* level so the 8-page exercise shares one server
    and preserves any server-side state mutations (validate, save, etc.) across
    tests within this module.
    """
    if not _spa_built():
        pytest.skip("SPA not built — run `make frontend-build` (or `make e2e`) first")

    if not _EXERCISE_FIXTURE_SRC.exists():
        pytest.skip("Exercise fixture missing — run: uv run python scripts/generate_exercise_fixture.py")

    data_root = tmp_path_factory.mktemp("exercise-data")
    cache_root = tmp_path_factory.mktemp("exercise-cache")
    config_root = tmp_path_factory.mktemp("exercise-config")
    source_root = tmp_path_factory.mktemp("exercise-source")

    # Copy the exercise-fixture project into source_root.
    dest = source_root / _PROJECT_ID
    shutil.copytree(_EXERCISE_FIXTURE_SRC, dest)

    # Pre-place labeled-lane envelopes in data_root/labeled-projects/
    # so the SPA's load_labeled lane finds them without running OCR.
    labeled_dir = data_root / "labeled-projects" / _PROJECT_ID
    labeled_dir.mkdir(parents=True, exist_ok=True)
    for env_src in sorted((_EXERCISE_FIXTURE_SRC / "page-images").glob("*.json")):
        shutil.copy2(env_src, labeled_dir / env_src.name)

    port = _pick_free_port()
    settings = Settings(
        host="127.0.0.1",
        port=port,
        data_root=data_root,
        cache_root=cache_root,
        config_root=config_root,
        source_projects_root=source_root,
        mode="normal",
    )

    app = build_app(settings)
    import uvicorn

    config = uvicorn.Config(app, host=settings.host, port=settings.port, log_level="warning")
    server = uvicorn.Server(config)
    thread = threading.Thread(target=server.run, daemon=True)
    thread.start()

    base_url = f"http://{settings.host}:{settings.port}"
    try:
        _wait_until(f"{base_url}/healthz")
    except RuntimeError:
        server.should_exit = True
        thread.join(timeout=2)
        raise

    # Load the exercise project into the server's session state.
    r = httpx.post(
        f"{base_url}/api/projects/source-root",
        json={"path": str(source_root)},
        timeout=10,
    )
    assert r.status_code in (200, 204), f"source-root POST failed: {r.status_code} {r.text}"

    r = httpx.post(
        f"{base_url}/api/projects/load",
        json={"project_root": str(dest)},
        timeout=30,
    )
    assert r.status_code == 200, f"load project failed: {r.status_code} {r.text}"

    yield ExerciseServer(
        base_url=base_url,
        settings=settings,
        source_root=source_root,
        data_root=data_root,
    )

    server.should_exit = True
    thread.join(timeout=5)


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _page_url(base_url: str, pageno: int) -> str:
    return f"{base_url}/projects/{_PROJECT_ID}/pages/pageno/{pageno}"


def _goto_project_page(page: Page, base_url: str, pageno: int, *, timeout: int = 20_000) -> None:
    """Navigate to the project page and wait for the shell to mount."""
    page.goto(_page_url(base_url, pageno), timeout=timeout)
    page.wait_for_selector('[data-testid="project-page"]', timeout=timeout)


def _wait_for_line_cards(page: Page, *, min_count: int = 1, timeout: int = 15_000) -> int:
    """Wait until at least ``min_count`` worklist rows are visible. Returns count.

    The ``WordMatchView`` (``line-card-*`` testids) uses a virtualizer that
    renders zero items when its container is ``display:none``.  The Drawer
    worklist (``worklist-row-*``) is always visible and uses no virtualizer,
    making it a reliable proxy for "the server returned line data for this page".

    Note: the worklist default filter is "unvalidated"; on page 1 the fixture
    pre-validates line 0, so the worklist shows lines 1–3 (3 rows).  The
    minimum expectation is therefore ``>= 1`` regardless of page.
    """
    try:
        page.wait_for_selector('[data-testid^="worklist-row-"]', timeout=timeout)
        return page.locator('[data-testid^="worklist-row-"]').count()
    except Exception:
        return 0


# ---------------------------------------------------------------------------
# Per-page common workflow (parameterised over pages 1-8)
# ---------------------------------------------------------------------------


@pytest.mark.e2e
@pytest.mark.parametrize("pageno", list(range(1, _TOTAL_PAGES + 1)))
def test_per_page_common_workflow(
    exercise_server: ExerciseServer,
    page: Page,
    pageno: int,
) -> None:
    """Per-page workflow: load → image → checkboxes → filter → nav-next.

    Exercises:
    1. Navigate to page ``pageno`` and verify the project-page shell renders.
    2. Verify the image viewport is present.
    3. Toggle the layer-lines and layer-words checkboxes on and back off.
    4. Cycle through the match-filter modes (Unvalidated → Mismatched → All).
    5. Verify line cards render (the fixture has labeled envelopes).
    6. On the last page (8): verify the next-page button is disabled or
       that clicking it leaves the URL unchanged (navigation edge case).
    """
    _goto_project_page(page, exercise_server.base_url, pageno)

    # 1. Image viewport present.
    page.wait_for_selector('[data-testid="image-viewport"]', timeout=10_000)

    # 2. Layer checkboxes — toggle lines off and back on.
    lines_cb = page.locator('[data-testid="layer-lines-checkbox"]').first
    if lines_cb.is_visible():
        lines_cb.click()
        time.sleep(0.15)
        lines_cb.click()  # restore
        time.sleep(0.15)

    # 3. Match-filter toggle — cycle through all three modes.
    for filter_testid in [
        "match-filter-unvalidated",
        "match-filter-mismatched",
        "match-filter-all",
    ]:
        btn = page.locator(f'[data-testid="{filter_testid}"]').first
        if btn.is_visible():
            btn.click()
            time.sleep(0.1)

    # 4. Verify line cards appeared (labeled envelopes → real content).
    count = _wait_for_line_cards(page, min_count=1)
    assert count >= 1, (
        f"Page {pageno}: expected at least 1 line card, got {count}. "
        f"Check that generate_exercise_fixture.py was run and envelopes are present."
    )

    # 5. Navigation edge case: on last page, next-page must be disabled.
    if pageno == _TOTAL_PAGES:
        # The real (non-stub) next button.
        next_btn = page.locator('[data-testid="nav-next-button"]:not([data-testid-stub])').first
        if next_btn.is_visible():
            # Either disabled attribute, or clicking it leaves URL unchanged.
            url_before = page.url
            if next_btn.get_attribute("disabled") is None:
                next_btn.click()
                time.sleep(0.3)
                assert page.url == url_before or f"/pageno/{_TOTAL_PAGES}" in page.url, (
                    f"Last page next-click changed URL to {page.url!r}"
                )
    else:
        # Non-last page: click next, verify URL advances.
        next_btn = page.locator('[data-testid="nav-next-button"]:not([data-testid-stub])').first
        if next_btn.is_visible() and next_btn.get_attribute("disabled") is None:
            next_btn.click()
            page.wait_for_url(f"**/pageno/{pageno + 1}", timeout=10_000)
            assert f"/pageno/{pageno + 1}" in page.url


# ---------------------------------------------------------------------------
# Page 1 — deeper flow: Source Folder, OCR Config, Save Page
# ---------------------------------------------------------------------------


@pytest.mark.e2e
def test_page1_source_folder_dialog(exercise_server: ExerciseServer, page: Page) -> None:
    """Page 1: open Source Folder dialog, verify it shows a path, close."""
    _goto_project_page(page, exercise_server.base_url, 1)

    # Click the source-folder-button in the header.
    sfb = page.locator('[data-testid="source-folder-button"]').first
    sfb.wait_for(state="visible", timeout=10_000)
    sfb.click()

    # Wait for the dialog to appear (either the real dialog or the stub).
    # The real SourceFolderDialog shows source-folder-current-path-label.
    page.wait_for_selector(
        '[data-testid="source-folder-current-path-label"], [data-testid="source-folder-dialog"]',
        timeout=8_000,
    )

    # Verify the cancel button exists and close.
    cancel = page.locator('[data-testid="source-folder-cancel-button"]').first
    if cancel.is_visible():
        cancel.click()
    else:
        # Fallback: press Escape to dismiss.
        page.keyboard.press("Escape")

    time.sleep(0.2)


@pytest.mark.e2e
def test_page1_ocr_config_modal(exercise_server: ExerciseServer, page: Page) -> None:
    """Page 1: open OCR Config modal, verify model selects render, close."""
    _goto_project_page(page, exercise_server.base_url, 1)

    page.click('[data-testid="ocr-config-trigger-button"]')

    # Wait for detection model select (real or stub).
    page.wait_for_selector(
        '[data-testid="ocr-detection-model-select"]',
        timeout=10_000,
    )

    # Close via cancel button.
    cancel = page.locator('[data-testid="ocr-config-cancel-button"]').first
    if cancel.is_visible():
        cancel.click()
    else:
        page.keyboard.press("Escape")

    time.sleep(0.2)


@pytest.mark.e2e
def test_page1_save_page(exercise_server: ExerciseServer, page: Page) -> None:
    """Page 1: click Save Page button and verify the page-source-badge updates."""
    _goto_project_page(page, exercise_server.base_url, 1)
    _wait_for_line_cards(page)

    save_btn = page.locator('[data-testid="save-page-button"]').first
    save_btn.wait_for(state="visible", timeout=10_000)

    # Record badge text before save (currently unused; kept for future assertions).
    badge = page.locator('[data-testid="page-source-badge"]').first
    _badge_before = badge.text_content() if badge.is_visible() else None

    save_btn.click()

    # Wait a moment for the save to complete (the SPA persists to disk).
    time.sleep(1.0)

    # The badge should either remain "LABELED" (already saved) or transition
    # from a transient state back to "LABELED".
    if badge.is_visible():
        badge_after = badge.text_content()
        assert badge_after in ("LABELED", "CACHED", "RAW OCR", "LOADING…"), (
            f"Unexpected badge text after save: {badge_after!r}"
        )


@pytest.mark.e2e
def test_page1_export_dialog(exercise_server: ExerciseServer, page: Page) -> None:
    """Page 1: open Export dialog, verify it renders, close without running."""
    _goto_project_page(page, exercise_server.base_url, 1)
    _wait_for_line_cards(page)

    export_btn = page.locator('[data-testid="export-button"]').first
    export_btn.wait_for(state="visible", timeout=10_000)
    export_btn.click()

    # Wait for the export dialog to mount.
    page.wait_for_selector('[data-testid="export-dialog"]', timeout=10_000)

    # Verify scope radios exist.
    assert page.locator('[data-testid="export-scope-current"]').count() > 0
    assert page.locator('[data-testid="export-scope-all"]').count() > 0

    # Close without running the export.
    close_btn = page.locator('[data-testid="export-close-button"]').first
    if close_btn.is_visible():
        close_btn.click()
    else:
        page.keyboard.press("Escape")

    time.sleep(0.2)


# ---------------------------------------------------------------------------
# Page 1 — word inspect flow
# ---------------------------------------------------------------------------


@pytest.mark.e2e
def test_page1_inspect_word(exercise_server: ExerciseServer, page: Page) -> None:
    """Page 1: click edit-word-button for word (0, 0), verify dialog opens."""
    _goto_project_page(page, exercise_server.base_url, 1)
    count = _wait_for_line_cards(page)
    assert count >= 1, "Need at least one line card for word inspection"

    # Click the edit button for line 0, word 0.
    edit_btn = page.locator('[data-testid="edit-word-button-0-0"]').first
    edit_btn.wait_for(state="visible", timeout=10_000)
    edit_btn.click()

    # Wait for the dialog to open.
    page.wait_for_selector(
        '[data-testid="dialog-header-label"], [data-testid="dialog-close-button"]',
        timeout=10_000,
    )

    # Close the dialog.
    close_btn = page.locator('[data-testid="dialog-close-button"]').first
    if close_btn.is_visible():
        close_btn.click()
    else:
        page.keyboard.press("Escape")

    time.sleep(0.2)


@pytest.mark.e2e
def test_page1_validate_line(exercise_server: ExerciseServer, page: Page) -> None:
    """Page 1: click line-validate-button-0 and verify it flips state."""
    _goto_project_page(page, exercise_server.base_url, 1)
    _wait_for_line_cards(page)

    validate_btn = page.locator('[data-testid="line-validate-button-0"]').first
    validate_btn.wait_for(state="visible", timeout=10_000)

    # Click validate.
    validate_btn.click()
    time.sleep(0.5)

    # The button should still be present (it toggles).
    assert validate_btn.is_visible(), "Validate button disappeared after click"


# ---------------------------------------------------------------------------
# Page 3 — editing flow (OCR errors introduced on page index 2 = pageno 3)
# ---------------------------------------------------------------------------


@pytest.mark.e2e
def test_page3_filter_shows_mismatches(exercise_server: ExerciseServer, page: Page) -> None:
    """Page 3: switching to Mismatched filter shows mismatched words.

    The exercise fixture introduces OCR errors on page index 2 (pageno 3):
    'colonists' → 'coloniats', 'professed' → 'profcssed'.  Switching to the
    Mismatched filter should either filter to those lines or show all lines
    (if none are validated yet — the exact behaviour depends on the filter
    implementation).
    """
    _goto_project_page(page, exercise_server.base_url, 3)
    _wait_for_line_cards(page)

    # Switch to Mismatched filter.
    mismatch_btn = page.locator('[data-testid="match-filter-mismatched"]').first
    mismatch_btn.wait_for(state="visible", timeout=10_000)
    mismatch_btn.click()
    time.sleep(0.3)

    # Restore to All.
    all_btn = page.locator('[data-testid="match-filter-all"]').first
    if all_btn.is_visible():
        all_btn.click()


@pytest.mark.e2e
def test_page3_edit_gt_text(exercise_server: ExerciseServer, page: Page) -> None:
    """Page 3: type a change in gt-text-input-0-0, blur, verify the input holds the value."""
    _goto_project_page(page, exercise_server.base_url, 3)
    _wait_for_line_cards(page)

    gt_input = page.locator('[data-testid="gt-text-input-0-0"]').first
    gt_input.wait_for(state="visible", timeout=10_000)

    # Clear and type new value.
    original = gt_input.input_value()
    new_value = original + "X"  # append a marker character
    gt_input.triple_click()
    gt_input.fill(new_value)
    gt_input.blur()
    time.sleep(0.5)

    # Restore original value.
    gt_input.triple_click()
    gt_input.fill(original)
    gt_input.blur()
    time.sleep(0.3)


@pytest.mark.e2e
def test_page3_word_dialog_nudge(exercise_server: ExerciseServer, page: Page) -> None:
    """Page 3: open word-edit dialog and nudge bbox left once, then close."""
    _goto_project_page(page, exercise_server.base_url, 3)
    _wait_for_line_cards(page)

    edit_btn = page.locator('[data-testid="edit-word-button-0-0"]').first
    edit_btn.wait_for(state="visible", timeout=10_000)
    edit_btn.click()

    # Wait for dialog.
    page.wait_for_selector(
        '[data-testid="dialog-close-button"]',
        timeout=10_000,
    )

    # Try to nudge left (data-testid="dialog-nudge-left-minus-button").
    nudge_btn = page.locator('[data-testid="dialog-nudge-left-minus-button"]').first
    if nudge_btn.is_visible():
        nudge_btn.click()
        time.sleep(0.2)

    # Apply + close.
    apply_btn = page.locator('[data-testid="dialog-apply-close-button"]').first
    if apply_btn.is_visible():
        apply_btn.click()
    else:
        close_btn = page.locator('[data-testid="dialog-close-button"]').first
        if close_btn.is_visible():
            close_btn.click()
        else:
            page.keyboard.press("Escape")

    time.sleep(0.3)


# ---------------------------------------------------------------------------
# Page 5 — erase mode flow (OCR errors on this page too)
# ---------------------------------------------------------------------------


@pytest.mark.e2e
def test_page5_erase_mode_toggle(exercise_server: ExerciseServer, page: Page) -> None:
    """Page 5: toggle erase-pixels-button on, then press Escape to exit."""
    _goto_project_page(page, exercise_server.base_url, 5)
    _wait_for_line_cards(page)

    erase_btn = page.locator('[data-testid="erase-pixels-button"]').first
    erase_btn.wait_for(state="visible", timeout=10_000)

    # Activate erase mode.
    erase_btn.click()
    time.sleep(0.2)

    aria_pressed = erase_btn.get_attribute("aria-pressed")
    # Should be "true" when active (ImageTabsHeader sets this).
    if aria_pressed is not None:
        assert aria_pressed == "true", (
            f"Expected erase-pixels-button aria-pressed='true' after click, got {aria_pressed!r}"
        )

    # Press Escape to exit erase mode.
    page.keyboard.press("Escape")
    time.sleep(0.2)


# ---------------------------------------------------------------------------
# Navigation continuity — pages 1→3→6 in sequence
# ---------------------------------------------------------------------------


@pytest.mark.e2e
def test_navigation_continuity(exercise_server: ExerciseServer, page: Page) -> None:
    """Navigate p1→p3→p6 using the nav-next/prev controls.

    Verifies that the URL updates correctly on each navigation step and
    that the project-page shell remains healthy throughout.
    """
    # Start at page 1.
    _goto_project_page(page, exercise_server.base_url, 1)

    # Navigate via the nav-page-input "Go To" box to page 3.
    nav_input = page.locator('[data-testid="nav-page-input"]:not([data-testid-stub])').first
    if nav_input.is_visible():
        nav_input.triple_click()
        nav_input.fill("3")
        goto_btn = page.locator('[data-testid="nav-goto-button"]:not([data-testid-stub])').first
        if goto_btn.is_visible():
            goto_btn.click()
            page.wait_for_url("**/pageno/3", timeout=10_000)
            assert "/pageno/3" in page.url

    # From page 3, navigate to page 6 via keyboard shortcut Ctrl+ArrowRight x3.
    # (Each Ctrl+ArrowRight advances one page.)
    for _ in range(3):
        page.keyboard.press("Control+ArrowRight")
        time.sleep(0.3)

    # Should be at page 6 now.
    page.wait_for_selector('[data-testid="project-page"]', timeout=10_000)

    # The project-page shell must still be healthy.
    assert page.locator('[data-testid="project-page"]').is_visible()
