/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/api/projects": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List Projects
     * @description ``GET /api/projects`` — enumerate + describe selection state.
     *
     *     Spec §5.2 lines 208-211. Pure read; never mutates the carrier.
     *
     *     The "is the active project under the configured root?" check uses
     *     ``_is_under_root`` so an off-root active project (e.g. one set via
     *     ``--project`` CLI override pointing outside the configured
     *     ``source_projects_root``) shows up as ``selected: None`` — the SPA
     *     dropdown can't mark an entry it doesn't display.
     */
    get: operations["list_projects_api_projects_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/projects/load": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Load Project
     * @description ``POST /api/projects/load`` — validate path, swap carrier.
     *
     *     Validation order (cheapest-first; the order is observable via the
     *     error tag returned):
     *
     *     1. Source root configured. If
     *        ``settings.source_projects_root is None``, no path can be
     *        "under it" → ``400 project_outside_source_root``.
     *     2. Path is under source root. ``_is_under_root`` resolves both
     *        paths, so ``..`` traversal is rejected here. → either
     *        ``400 project_outside_source_root`` (resolved path is outside)
     *        or ``404 project_not_found`` (resolved path doesn't exist —
     *        ``resolve()`` succeeded but the dir is gone).
     *     3. Path is a directory. We reach this only after the under-root
     *        check passed AND the path resolves; if it's a regular file
     *        (e.g. someone POSTed ``regular_file.txt``) → ``400
     *        invalid_project_dir``.
     *     4. Carrier swap via ``set_active_project``. The carrier
     *        re-validates internally — defensive belt-and-suspenders for the
     *        TOCTOU race where the dir vanished between our ``is_dir()`` and
     *        the carrier's. On rare TOCTOU, we surface ``404
     *        project_not_found`` (operator-actionable label, same shape the
     *        lifespan hook uses for the same race in slice 3).
     *
     *     Slice 5 (this iter) extends slice 4 to also:
     *
     *     - Build the full ``Project`` model from disk (``pages.json`` /
     *       ``pages_manifest.json`` ground truth + image-file scan +
     *       optional ``project.json`` saved metadata) via
     *       ``build_project_from_directory``.
     *     - Stash the model on ``ProjectState`` via ``set_loaded_project``.
     *     - Return a ``LoadProjectResponse{project, current_page_index, generation}``
     *       response (replacing the slice-4 ``LoadProjectResponseStub``).
     *
     *     Session-state writeback is still omitted in slice 5: the
     *     ``save_session_state`` call wants to record both the project path
     *     AND the page index that the SPA actually displayed. Slice 5 stops
     *     short of the page-payload step (M3 territory: real OCR / image
     *     cache / encode dims), so the index we'd record is just whatever
     *     ``build_project_from_directory`` clamped — accurate, but the spec
     *     intentionally bundles session-state with the page-payload step.
     *     M3 will land both.
     */
    post: operations["load_project_api_projects_load_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/projects/{project_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Project By Id
     * @description ``GET /api/projects/{project_id}`` — return the loaded ``Project``.
     *
     *     Spec §02-backend.md line 220 — returns the loaded ``Project`` model
     *     by ``project_id``. This is M2-proper's read endpoint that pairs
     *     with slice-5's load handler: load mutates ``ProjectState``, GET
     *     reads it back.
     *
     *     Behavior:
     *
     *     - If ``ProjectState.loaded_project is None`` → ``404 project_not_found``.
     *       The spec ties ``project_not_found`` to "no project with that id is
     *       open"; the no-project-loaded case is a special instance of the
     *       same ("zero projects loaded means no id can match").
     *     - If ``loaded_project.project_id != project_id`` → ``404
     *       project_not_found``. The single-``ProjectState`` carrier addresses
     *       exactly one project at a time; asking for a different id is the
     *       same shape of miss.
     *     - Otherwise → ``200`` with the ``Project`` JSON, identical to the
     *       ``project`` field of ``LoadProjectResponse``.
     *
     *     No on-demand load: this route never reaches the filesystem. To open
     *     a project, the SPA calls ``POST /api/projects/load`` first.
     *
     *     The trailing-slash variant is NOT registered — FastAPI normalizes
     *     ``/api/projects/foo/`` to ``/api/projects/foo``, so a single route
     *     suffices.
     */
    get: operations["get_project_by_id_api_projects__project_id__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/projects/source-root": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Set Source Projects Root
     * @description ``POST /api/projects/source-root`` — stub; M2-proper config milestone.
     */
    post: operations["set_source_projects_root_api_projects_source_root_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/projects/{project_id}/pages/{page_index}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Page
     * @description ``GET /api/projects/{id}/pages/{idx}`` — stub; M3.
     */
    get: operations["get_page_api_projects__project_id__pages__page_index__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/projects/{project_id}/pages/{page_index}/save": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Save Page
     * @description ``POST .../save`` — stub; M3.
     */
    post: operations["save_page_api_projects__project_id__pages__page_index__save_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/projects/{project_id}/save-all": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Save Project
     * @description ``POST /api/projects/{id}/save-all`` — stub; M3.
     */
    post: operations["save_project_api_projects__project_id__save_all_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/projects/{project_id}/pages/{page_index}/reload-ocr": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Reload Ocr
     * @description ``POST .../reload-ocr`` — stub; M3.
     */
    post: operations["reload_ocr_api_projects__project_id__pages__page_index__reload_ocr_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/projects/{project_id}/pages/{page_index}/rematch-gt": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Rematch Gt
     * @description ``POST .../rematch-gt`` — stub; M3.
     */
    post: operations["rematch_gt_api_projects__project_id__pages__page_index__rematch_gt_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/projects/{project_id}/pages/{page_index}/words/{line_index}/{word_index}/gt": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Update Word Ground Truth
     * @description ``POST .../words/{li}/{wi}/gt`` — stub; M3.
     */
    post: operations["update_word_ground_truth_api_projects__project_id__pages__page_index__words__line_index___word_index__gt_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/projects/{project_id}/pages/{page_index}/words/{line_index}/{word_index}/style": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Apply Style
     * @description ``POST .../words/{li}/{wi}/style`` — stub; M3.
     */
    post: operations["apply_style_api_projects__project_id__pages__page_index__words__line_index___word_index__style_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/projects/{project_id}/pages/{page_index}/words/{line_index}/{word_index}/component": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Apply Component
     * @description ``POST .../words/{li}/{wi}/component`` — stub; M3.
     */
    post: operations["apply_component_api_projects__project_id__pages__page_index__words__line_index___word_index__component_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/projects/{project_id}/pages/{page_index}/words/{line_index}/{word_index}/validated": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Toggle Validated
     * @description ``POST .../words/{li}/{wi}/validated`` — stub; M3.
     */
    post: operations["toggle_validated_api_projects__project_id__pages__page_index__words__line_index___word_index__validated_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/projects/{project_id}/pages/{page_index}/words/validate-batch": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Validate Batch
     * @description ``POST .../words/validate-batch`` — stub; M3.
     */
    post: operations["validate_batch_api_projects__project_id__pages__page_index__words_validate_batch_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/projects/{project_id}/pages/{page_index}/words/add": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Add Word
     * @description ``POST .../words/add`` — stub; M3.
     */
    post: operations["add_word_api_projects__project_id__pages__page_index__words_add_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/projects/{project_id}/pages/{page_index}/words/{line_index}/{word_index}/rebox": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Rebox Word
     * @description ``POST .../words/{li}/{wi}/rebox`` — stub; M3.
     */
    post: operations["rebox_word_api_projects__project_id__pages__page_index__words__line_index___word_index__rebox_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/projects/{project_id}/pages/{page_index}/words/{line_index}/{word_index}/nudge": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Nudge Bbox
     * @description ``POST .../words/{li}/{wi}/nudge`` — stub; M3.
     */
    post: operations["nudge_bbox_api_projects__project_id__pages__page_index__words__line_index___word_index__nudge_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/projects/{project_id}/pages/{page_index}/words/{line_index}/{word_index}/split": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Split Word
     * @description ``POST .../words/{li}/{wi}/split`` — stub; M3.
     */
    post: operations["split_word_api_projects__project_id__pages__page_index__words__line_index___word_index__split_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/projects/{project_id}/pages/{page_index}/words/{line_index}/{word_index}/merge": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Merge Words
     * @description ``POST .../words/{li}/{wi}/merge`` — stub; M3.
     */
    post: operations["merge_words_api_projects__project_id__pages__page_index__words__line_index___word_index__merge_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/projects/{project_id}/pages/{page_index}/words/{line_index}/{word_index}/erase-pixels": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Erase Pixels
     * @description ``POST .../words/{li}/{wi}/erase-pixels`` — stub; M3.
     */
    post: operations["erase_pixels_api_projects__project_id__pages__page_index__words__line_index___word_index__erase_pixels_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/projects/{project_id}/pages/{page_index}/lines/{line_index}/copy-gt": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Copy Line Gt
     * @description ``POST .../lines/{li}/copy-gt`` — stub; M3.
     */
    post: operations["copy_line_gt_api_projects__project_id__pages__page_index__lines__line_index__copy_gt_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/projects/{project_id}/pages/{page_index}/delete": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Delete Scope
     * @description ``POST .../delete`` — stub; M3.
     */
    post: operations["delete_scope_api_projects__project_id__pages__page_index__delete_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/projects/{project_id}/pages/{page_index}/merge": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Merge Scope
     * @description ``POST .../merge`` — stub; M3.
     */
    post: operations["merge_scope_api_projects__project_id__pages__page_index__merge_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/projects/{project_id}/pages/{page_index}/paragraphs/{paragraph_index}/split-after-line": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Split Paragraph After Line
     * @description ``POST .../paragraphs/{pi}/split-after-line`` — stub; M3.
     */
    post: operations["split_paragraph_after_line_api_projects__project_id__pages__page_index__paragraphs__paragraph_index__split_after_line_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/projects/{project_id}/pages/{page_index}/lines/{line_index}/split-after-word": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Split Line After Word
     * @description ``POST .../lines/{li}/split-after-word`` — stub; M3.
     */
    post: operations["split_line_after_word_api_projects__project_id__pages__page_index__lines__line_index__split_after_word_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/projects/{project_id}/pages/{page_index}/lines/{line_index}/split-with-selected": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Split Line With Selected Words
     * @description ``POST .../lines/{li}/split-with-selected`` — stub; M3.
     */
    post: operations["split_line_with_selected_words_api_projects__project_id__pages__page_index__lines__line_index__split_with_selected_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/projects/{project_id}/pages/{page_index}/words/group-into-paragraph": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Group Selected Words Into New Paragraph
     * @description ``POST .../words/group-into-paragraph`` — stub; M3.
     */
    post: operations["group_selected_words_into_new_paragraph_api_projects__project_id__pages__page_index__words_group_into_paragraph_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/projects/{project_id}/pages/{page_index}/refine": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Refine Scope
     * @description ``POST .../refine`` — stub; M3.
     */
    post: operations["refine_scope_api_projects__project_id__pages__page_index__refine_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/projects/{project_id}/export": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Start Export
     * @description ``POST /api/projects/{id}/export`` — stub; M3.
     */
    post: operations["start_export_api_projects__project_id__export_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/jobs": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List Jobs
     * @description ``GET /api/jobs`` — stub; M3.
     */
    get: operations["list_jobs_api_jobs_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/jobs/{job_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Job
     * @description ``GET /api/jobs/{job_id}`` — stub; M3.
     */
    get: operations["get_job_api_jobs__job_id__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/ocr-config": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Ocr Config
     * @description Return an OCR-config snapshot.
     *
     *     Spec §02-backend.md §5.8 line 319. The response body composes the
     *     iter-7 DTOs; ``selection_reason`` is computed from the slice-8c-iii
     *     discovery pipeline (HF probe + local-models walk +
     *     ``pick_default_keys``). Option lists remain stock-only — surfacing
     *     HF / local options is slice 8c-iv-b+ work.
     *
     *     Slice 8c-iv-a wires the ``OCRConfigCarrier``: the GET reads the
     *     *currently selected* triple from the carrier (defaults to
     *     ``("stock", "stock", None)`` until a POST mutates it), and a
     *     subsequent GET reflects the POST's selection within the same
     *     process. Disk-side persistence is slice 8c-iv-b.
     */
    get: operations["get_ocr_config_api_ocr_config_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/ocr-config/models": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Post Ocr Config Models
     * @description Validate + persist OCR model selection.
     *
     *     Spec §02-backend.md §5.8 line 320. The route shape is canonical;
     *     selection persists in two layers:
     *
     *     - **In-process** (slice 8c-iv-a): ``OCRConfigCarrier`` so a
     *       subsequent ``GET /api/ocr-config`` in the same process reflects
     *       the change.
     *     - **On-disk** (slice 8c-iv-b, this slice): ``ocr_config.json``
     *       sidecar at ``<data_root>/ocr_config.json`` so the selection
     *       survives a restart. The save runs **after** ``set_models``
     *       reports an actual state change — idempotent re-POSTs of the
     *       same triple skip the disk I/O.
     *
     *     Save errors are logged-and-swallowed inside ``save_ocr_config``
     *     (spec §7a) so a sidecar-write failure cannot turn a 200 OCR-config
     *     POST into a 500. The user's selection still takes effect for the
     *     live session; the operator sees the failure via the stable
     *     WARNING substring ``ocr_config_save_failed``.
     *
     *     Unknown keys → 400. The wire body's ``selection_reason`` is the
     *     slice-8c-iii-c picker output.
     */
    post: operations["post_ocr_config_models_api_ocr_config_models_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/ocr-config/rescan": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Post Ocr Config Rescan
     * @description Re-run model discovery and reconcile the carrier (slice 8c-v-b).
     *
     *     Spec ``specs/02-backend.md §5.8`` line 321. The handler walks the
     *     discovery pipeline fresh (HF probe + local-models tree) so a model
     *     pair that landed on disk after startup surfaces, and a pair that was
     *     deleted between calls no longer does.
     *
     *     Carrier reconciliation: if the currently-selected detection /
     *     recognition key still appears in the freshly-discovered option list,
     *     it is preserved; otherwise it falls back to ``"stock"`` (always
     *     present). The carrier is mutated only on real change — idempotent
     *     rescans (no surface-set churn) skip the disk write the same way an
     *     idempotent ``POST /models`` does.
     */
    post: operations["post_ocr_config_rescan_api_ocr_config_rescan_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /**
     * AddWordRequest
     * @description Spec §2 lines 308-311.
     */
    AddWordRequest: {
      /** Line Index */
      line_index?: number | null;
      bbox: components["schemas"]["BBox"];
      /**
       * Text
       * @default
       */
      text: string;
    };
    /**
     * ApplyComponentRequest
     * @description Spec §2 lines 293-295.
     */
    ApplyComponentRequest: {
      /** Component */
      component: string;
      /** Enabled */
      enabled: boolean;
    };
    /**
     * ApplyStyleRequest
     * @description Spec §2 lines 288-290.
     */
    ApplyStyleRequest: {
      /** Style */
      style: string;
      /**
       * Scope
       * @default whole
       * @enum {string}
       */
      scope: "whole" | "part";
    };
    /**
     * BBox
     * @description Image-coordinate bounding box — spec §1 ``BBox``.
     *
     *     Top-left origin, source image pixels (not display pixels).
     */
    BBox: {
      /** X */
      x: number;
      /** Y */
      y: number;
      /** Width */
      width: number;
      /** Height */
      height: number;
    };
    /**
     * CachedImageSet
     * @description Optional filenames for each cached image type — spec §1 ``CachedImageSet``.
     */
    CachedImageSet: {
      /** Original */
      original?: string | null;
      /** Lines */
      lines?: string | null;
      /** Paragraphs */
      paragraphs?: string | null;
      /** Words */
      words?: string | null;
      /** Matched Words */
      matched_words?: string | null;
    };
    /**
     * CopyLineGtRequest
     * @description Spec §2 line 337.
     */
    CopyLineGtRequest: {
      /**
       * Direction
       * @enum {string}
       */
      direction: "gt_to_ocr" | "ocr_to_gt";
    };
    /**
     * DeleteScopeRequest
     * @description Spec §2 lines 340-344.
     */
    DeleteScopeRequest: {
      /**
       * Scope
       * @enum {string}
       */
      scope: "paragraph" | "line" | "word";
      /**
       * Paragraph Indices
       * @default []
       */
      paragraph_indices: number[];
      /**
       * Line Indices
       * @default []
       */
      line_indices: number[];
      /**
       * Word Indices
       * @default []
       */
      word_indices: [number, number][];
    };
    /**
     * EncodedDims
     * @description Source and display dimensions with scale factor — spec §1 ``EncodedDims``.
     *
     *     Algorithm matches legacy ``_compute_encoded_dimensions``.
     */
    EncodedDims: {
      /** Src Width */
      src_width: number;
      /** Src Height */
      src_height: number;
      /** Display Width */
      display_width: number;
      /** Display Height */
      display_height: number;
      /** Scale */
      scale: number;
    };
    /**
     * ErasePixelsRequest
     * @description Spec §2 lines 330-332.
     */
    ErasePixelsRequest: {
      bbox: components["schemas"]["BBox"];
      /**
       * Fill Value
       * @default 255
       */
      fill_value: number;
    };
    /**
     * ExportRequest
     * @description Body for ``POST /api/projects/{id}/export`` — spec §2 lines 414-420.
     */
    ExportRequest: {
      scope: components["schemas"]["ExportScope"];
      /**
       * Style Filters
       * @default []
       */
      style_filters: string[];
      /** Component Filter */
      component_filter?: string | null;
      /**
       * Include Classification
       * @default false
       */
      include_classification: boolean;
      /**
       * Detection Only
       * @default false
       */
      detection_only: boolean;
      /**
       * Recognition Only
       * @default false
       */
      recognition_only: boolean;
    };
    /**
     * ExportResponse
     * @description Response for export — spec §2 lines 422-423.
     */
    ExportResponse: {
      /** Job Id */
      job_id: string;
    };
    /**
     * ExportScope
     * @description Export scope discriminant — spec §2 lines 411-412.
     * @enum {string}
     */
    ExportScope: "current" | "all_validated";
    /**
     * GetOCRConfigResponse
     * @description OCR config snapshot — spec lines 385-396.
     *
     *     Returned from ``GET /api/ocr-config`` and from both POST
     *     endpoints (so the frontend always sees the post-mutation state).
     *     ``selection_reason`` is the explanation string the OCRConfigModal
     *     shows under the selected pair — pinning the literal set lets the
     *     frontend exhaustively switch on it for tooltip text.
     */
    GetOCRConfigResponse: {
      /** Detection Options */
      detection_options: components["schemas"]["OCRModelOption"][];
      /** Recognition Options */
      recognition_options: components["schemas"]["OCRModelOption"][];
      /** Selected Detection */
      selected_detection: string;
      /** Selected Recognition */
      selected_recognition: string;
      /** Hf Pinned Revision */
      hf_pinned_revision: string | null;
      /**
       * Selection Reason
       * @enum {string}
       */
      selection_reason:
        | "hf-latest"
        | "hf-only"
        | "local-newer-than-hf"
        | "local-only-hf-unreachable"
        | "hf-unreachable-no-local"
        | "stock-fallback";
    };
    /**
     * GroupSelectedWordsIntoNewParagraphRequest
     * @description Spec §2 lines 364-365.
     */
    GroupSelectedWordsIntoNewParagraphRequest: {
      /** Word Indices */
      word_indices: [number, number][];
    };
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components["schemas"]["ValidationError"][];
    };
    /**
     * Job
     * @description Background job record — spec §1 ``Job``. Mirrors pgdp-prep ``core/models.py``.
     */
    Job: {
      /** Id */
      id: string;
      type: components["schemas"]["JobType"];
      /** Project Id */
      project_id: string | null;
      status: components["schemas"]["JobStatus"];
      progress: components["schemas"]["JobProgress"];
      /** Error Message */
      error_message?: string | null;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /**
       * Updated At
       * Format: date-time
       */
      updated_at: string;
    };
    /**
     * JobProgress
     * @description Progress counters for a running job — spec §1 ``JobProgress``.
     */
    JobProgress: {
      /**
       * Current
       * @default 0
       */
      current: number;
      /**
       * Total
       * @default 0
       */
      total: number;
      /** Current Page */
      current_page?: number | null;
      /**
       * Message
       * @default
       */
      message: string;
    };
    /**
     * JobStatus
     * @description Job lifecycle state — spec §1 ``JobStatus``.
     * @enum {string}
     */
    JobStatus: "queued" | "running" | "complete" | "error";
    /**
     * JobType
     * @description Discriminant for background job kind — spec §1 ``JobType``.
     * @enum {string}
     */
    JobType:
      | "refine_bboxes_page"
      | "expand_refine_bboxes_page"
      | "reload_ocr_page"
      | "export"
      | "save_project"
      | "refine_bboxes_project";
    /**
     * LineFilter
     * @description Line display filter — spec §1 ``LineFilter``.
     * @enum {string}
     */
    LineFilter: "unvalidated" | "mismatched" | "all";
    /**
     * LineMatch
     * @description Per-line rollup with pre-computed counters — spec §1 ``LineMatch``.
     */
    LineMatch: {
      /** Line Index */
      line_index: number;
      /** Paragraph Index */
      paragraph_index: number | null;
      /** Ocr Line Text */
      ocr_line_text: string;
      /** Ground Truth Line Text */
      ground_truth_line_text: string;
      /** Word Matches */
      word_matches: components["schemas"]["WordMatch"][];
      overall_match_status: components["schemas"]["MatchStatus"];
      /** Exact Count */
      exact_count: number;
      /** Fuzzy Count */
      fuzzy_count: number;
      /** Mismatch Count */
      mismatch_count: number;
      /** Unmatched Gt Count */
      unmatched_gt_count: number;
      /** Unmatched Ocr Count */
      unmatched_ocr_count: number;
      /** Validated Word Count */
      validated_word_count: number;
      /** Total Word Count */
      total_word_count: number;
      /** Is Fully Validated */
      is_fully_validated: boolean;
    };
    /**
     * ListProjectsResponse
     * @description Spec §2 lines 206-210.
     *
     *     - ``projects``: stable, sorted, deduped list per slice-4-starter.
     *     - ``selected``: ``project_id`` of the active project IF it lives
     *       under ``projects_root``; else ``None`` (the dropdown can only
     *       mark entries it actually shows).
     *     - ``projects_root``: the resolved root, or a sentinel empty path
     *       when ``Settings.source_projects_root is None``. The SPA's
     *       project-load controls render the un-configured case as "no
     *       source folder set" — sentinel ``Path("")`` keeps the response
     *       schema-compatible with the spec without an Optional field.
     *     - ``config_source``: provenance label. Slice 4 always emits
     *       ``"default"``; M2-proper's ``POST /api/projects/source-root``
     *       will flip it to ``"yaml"`` / ``"cli"``.
     */
    ListProjectsResponse: {
      /** Projects */
      projects: components["schemas"]["ProjectKey"][];
      /** Selected */
      selected: string | null;
      /**
       * Projects Root
       * Format: path
       */
      projects_root: string;
      /**
       * Config Source
       * @enum {string}
       */
      config_source: "yaml" | "cli" | "default";
    };
    /**
     * LoadProjectRequest
     * @description Spec §2 lines 217-219.
     *
     *     ``initial_page_index`` defaults to 0; M2-proper's expanded handler
     *     will use it to seed the first page. Slice 4 accepts the field so
     *     the wire schema stays stable, but ignores it (no page graph yet).
     */
    LoadProjectRequest: {
      /**
       * Project Root
       * Format: path
       */
      project_root: string;
      /**
       * Initial Page Index
       * @default 0
       */
      initial_page_index: number;
    };
    /**
     * MatchStatus
     * @description Per-word match result — spec §1 ``MatchStatus``.
     *
     *     Exactly five values, matching legacy ``WordMatch.match_status``.
     * @enum {string}
     */
    MatchStatus: "exact" | "fuzzy" | "mismatch" | "unmatched_ocr" | "unmatched_gt";
    /**
     * MergeScopeRequest
     * @description Spec §2 lines 346-349.
     */
    MergeScopeRequest: {
      /**
       * Scope
       * @enum {string}
       */
      scope: "paragraph" | "line";
      /**
       * Paragraph Indices
       * @default []
       */
      paragraph_indices: number[];
      /**
       * Line Indices
       * @default []
       */
      line_indices: number[];
    };
    /**
     * MergeWordsRequest
     * @description Spec §2 lines 327-328.
     */
    MergeWordsRequest: {
      /**
       * Direction
       * @enum {string}
       */
      direction: "left" | "right";
    };
    /**
     * NudgeBboxRequest
     * @description Spec §2 lines 316-321.
     */
    NudgeBboxRequest: {
      /**
       * Left
       * @default 0
       */
      left: number;
      /**
       * Right
       * @default 0
       */
      right: number;
      /**
       * Top
       * @default 0
       */
      top: number;
      /**
       * Bottom
       * @default 0
       */
      bottom: number;
      /**
       * Refine After
       * @default false
       */
      refine_after: boolean;
    };
    /**
     * OCRModelOption
     * @description One detection or recognition model entry — spec lines 377-383.
     *
     *     ``key`` is the opaque identifier the frontend round-trips on
     *     ``POST /api/ocr-config/models``: ``"stock"`` for the bundled
     *     DocTR weights, ``"hf:<name>"`` for HuggingFace-hosted weights
     *     (with ``revision`` carrying the pinned commit), ``"local:<path>"``
     *     for a local weights file. ``label`` is the user-visible string;
     *     ``source`` is the discriminant the picker UI uses for the badge
     *     color.
     */
    OCRModelOption: {
      /** Key */
      key: string;
      /** Label */
      label: string;
      /**
       * Source
       * @enum {string}
       */
      source: "stock" | "huggingface" | "local";
      /** Revision */
      revision?: string | null;
      /**
       * Is Default
       * @default false
       */
      is_default: boolean;
      /** Weights Id */
      weights_id?: string | null;
    };
    /**
     * OCRProvenance
     * @description OCR provenance block — nested, forward-compat with extra="ignore".
     */
    OCRProvenance: {
      /**
       * Engine
       * @default
       */
      engine: string;
      /**
       * Engine Version
       * @default
       */
      engine_version: string;
      /**
       * Models
       * @default []
       */
      models: string[];
      /** Config Fingerprint */
      config_fingerprint?: string | null;
    };
    /**
     * PagePayload
     * @description Full page data bundle returned by GET and POST page endpoints.
     *
     *     Spec §2 lines 241-250.
     */
    PagePayload: {
      record: components["schemas"]["PageRecord"];
      encoded: components["schemas"]["EncodedDims"];
      /** Line Matches */
      line_matches: components["schemas"]["LineMatch"][];
      /** Paragraph Indices */
      paragraph_indices: number[];
      /** Page Text Ocr */
      page_text_ocr: string;
      /** Page Text Gt */
      page_text_gt: string;
      /** Image Url */
      image_url: string;
      /** Overlay Urls */
      overlay_urls: {
        [key: string]: string;
      };
      /** Has Edited Image */
      has_edited_image: boolean;
    };
    /**
     * PageRecord
     * @description Per-page metadata — spec §1 ``PageRecord``.
     *
     *     The actual ``Page`` object lives in ``PageState`` in-memory and is
     *     NOT serialised here. Wire shapes that need page contents use
     *     ``PagePayload`` (defined in ``api/pages.py``).
     */
    PageRecord: {
      /** Page Index */
      page_index: number;
      /** Page Number */
      page_number: number;
      /**
       * Image Path
       * Format: path
       */
      image_path: string;
      /** @default ocr */
      page_source: components["schemas"]["PageSource"];
      /**
       * Ocr Failed
       * @default false
       */
      ocr_failed: boolean;
      ocr_provenance?: components["schemas"]["OCRProvenance"] | null;
      /** Saved Provenance */
      saved_provenance?: {
        [key: string]: unknown;
      } | null;
      /** @default {} */
      cached_images: components["schemas"]["CachedImageSet"];
    };
    /**
     * PageSource
     * @description How a page's OCR data was sourced — spec §1 ``PageSource``.
     * @enum {string}
     */
    PageSource: "ocr" | "cached_ocr" | "filesystem" | "fallback";
    /**
     * ProjectKey
     * @description One discoverable project. Spec §2 lines 212-216.
     *
     *     Mirrors ``core.project_enumeration.EnumeratedProject`` but with
     *     ``Path`` rendered as a string in JSON (FastAPI's default).
     */
    ProjectKey: {
      /** Project Id */
      project_id: string;
      /**
       * Project Root
       * Format: path
       */
      project_root: string;
      /** Label */
      label: string;
    };
    /**
     * ReboxWordRequest
     * @description Spec §2 lines 313-314.
     */
    ReboxWordRequest: {
      bbox: components["schemas"]["BBox"];
    };
    /**
     * RefineScopeRequest
     * @description Body for ``POST .../refine`` — spec §2 lines 371-378.
     */
    RefineScopeRequest: {
      /**
       * Scope
       * @enum {string}
       */
      scope: "page" | "paragraph" | "line" | "word";
      /**
       * Mode
       * @default refine
       * @enum {string}
       */
      mode: "refine" | "expand_then_refine" | "expand_only";
      /**
       * Padding Px
       * @default 2
       */
      padding_px: number;
      /**
       * Paragraph Indices
       * @default []
       */
      paragraph_indices: number[];
      /**
       * Line Indices
       * @default []
       */
      line_indices: number[];
      /**
       * Word Indices
       * @default []
       */
      word_indices: [number, number][];
    };
    /**
     * ReloadOCRRequest
     * @description Body for ``POST .../reload-ocr`` — spec §2 lines 275-276.
     */
    ReloadOCRRequest: {
      /**
       * Use Edited Image
       * @default false
       */
      use_edited_image: boolean;
    };
    /**
     * RematchGtRequest
     * @description Body for ``POST .../rematch-gt`` — spec §2 line 278. Empty body.
     */
    RematchGtRequest: Record<string, never>;
    /**
     * SaveFailure
     * @description One page's save failure record — spec §2 ``SaveFailure``.
     */
    SaveFailure: {
      /** Page Index */
      page_index: number;
      /** Page Number */
      page_number: number;
      /** Reason */
      reason: string;
    };
    /**
     * SavePageRequest
     * @description Body for ``POST /api/projects/{id}/pages/{idx}/save`` — spec §2 line 257.
     */
    SavePageRequest: {
      /**
       * Saved By
       * @default Save Page
       */
      saved_by: string;
    };
    /**
     * SavePageResponse
     * @description Response for ``POST .../save`` — spec §2 lines 258-260.
     */
    SavePageResponse: {
      page: components["schemas"]["PagePayload"];
      /**
       * Saved Path
       * Format: path
       */
      saved_path: string;
    };
    /**
     * SaveProjectResponse
     * @description Response for ``POST /api/projects/{id}/save-all`` — spec §2 lines 262-267.
     */
    SaveProjectResponse: {
      /** Saved Count */
      saved_count: number;
      /** Skipped Count */
      skipped_count: number;
      /** Failed Count */
      failed_count: number;
      /** Total Count */
      total_count: number;
      /**
       * Failures
       * @default []
       */
      failures: components["schemas"]["SaveFailure"][];
    };
    /**
     * SetOCRModelsRequest
     * @description Body of ``POST /api/ocr-config/models`` — spec lines 397-400.
     */
    SetOCRModelsRequest: {
      /** Detection Key */
      detection_key: string;
      /** Recognition Key */
      recognition_key: string;
      /** Hf Pinned Revision */
      hf_pinned_revision?: string | null;
    };
    /**
     * SetSourceProjectsRootRequest
     * @description Body for ``POST /api/projects/source-root`` — spec §2 line 230.
     */
    SetSourceProjectsRootRequest: {
      /**
       * Path
       * Format: path
       */
      path: string;
    };
    /**
     * SetSourceProjectsRootResponse
     * @description Response for ``POST /api/projects/source-root`` — spec §2 lines 232-234.
     */
    SetSourceProjectsRootResponse: {
      /**
       * Projects Root
       * Format: path
       */
      projects_root: string;
      /** Projects */
      projects: components["schemas"]["ProjectKey"][];
    };
    /**
     * SplitLineAfterWordRequest
     * @description Spec §2 lines 355-357.
     */
    SplitLineAfterWordRequest: {
      /** Line Index */
      line_index: number;
      /** After Word Index */
      after_word_index: number;
    };
    /**
     * SplitLineWithSelectedWordsRequest
     * @description Spec §2 lines 359-362.
     */
    SplitLineWithSelectedWordsRequest: {
      /** Line Index */
      line_index: number;
      /** Word Indices */
      word_indices: number[];
      /**
       * Mode
       * @enum {string}
       */
      mode: "extract_to_new" | "split_into_two";
    };
    /**
     * SplitParagraphAfterLineRequest
     * @description Spec §2 lines 351-353.
     */
    SplitParagraphAfterLineRequest: {
      /** Paragraph Index */
      paragraph_index: number;
      /** After Line Index */
      after_line_index: number;
    };
    /**
     * SplitWordRequest
     * @description Spec §2 lines 323-325.
     */
    SplitWordRequest: {
      /** X Fraction */
      x_fraction: number;
      /**
       * Direction
       * @enum {string}
       */
      direction: "horizontal" | "vertical";
    };
    /**
     * ToggleValidatedRequest
     * @description Spec §2 lines 297-298.
     */
    ToggleValidatedRequest: {
      /** Validated */
      validated?: boolean | null;
    };
    /**
     * UpdateWordGroundTruthRequest
     * @description Spec §2 line 285.
     */
    UpdateWordGroundTruthRequest: {
      /** Text */
      text: string;
    };
    /**
     * ValidateBatchRequest
     * @description Spec §2 lines 300-306.
     */
    ValidateBatchRequest: {
      /**
       * Scope
       * @enum {string}
       */
      scope: "page" | "paragraph" | "line" | "word";
      /** Line Index */
      line_index?: number | null;
      /**
       * Word Indices
       * @default []
       */
      word_indices: [number, number][];
      /**
       * Paragraph Indices
       * @default []
       */
      paragraph_indices: number[];
      /**
       * Line Indices
       * @default []
       */
      line_indices: number[];
      /** Validated */
      validated: boolean;
    };
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
      /** Input */
      input?: unknown;
      /** Context */
      ctx?: Record<string, never>;
    };
    /**
     * WordMatch
     * @description Per-word match result — spec §1 ``WordMatch``.
     */
    WordMatch: {
      /** Line Index */
      line_index: number;
      /** Word Index */
      word_index: number | null;
      /** Ocr Text */
      ocr_text: string;
      /** Ground Truth Text */
      ground_truth_text: string;
      match_status: components["schemas"]["MatchStatus"];
      /** Fuzz Score */
      fuzz_score?: number | null;
      /**
       * Is Validated
       * @default false
       */
      is_validated: boolean;
      /**
       * Text Style Labels
       * @default []
       */
      text_style_labels: string[];
      /**
       * Word Components
       * @default []
       */
      word_components: string[];
      bbox: components["schemas"]["BBox"];
      /** Word Id */
      word_id?: string | null;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  list_projects_api_projects_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ListProjectsResponse"];
        };
      };
    };
  };
  load_project_api_projects_load_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["LoadProjectRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_project_by_id_api_projects__project_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        project_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  set_source_projects_root_api_projects_source_root_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["SetSourceProjectsRootRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SetSourceProjectsRootResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_page_api_projects__project_id__pages__page_index__get: {
    parameters: {
      query?: {
        line_filter?: components["schemas"]["LineFilter"];
      };
      header?: never;
      path: {
        project_id: string;
        page_index: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PagePayload"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  save_page_api_projects__project_id__pages__page_index__save_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        project_id: string;
        page_index: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["SavePageRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SavePageResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  save_project_api_projects__project_id__save_all_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        project_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SaveProjectResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  reload_ocr_api_projects__project_id__pages__page_index__reload_ocr_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        project_id: string;
        page_index: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ReloadOCRRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PagePayload"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  rematch_gt_api_projects__project_id__pages__page_index__rematch_gt_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        project_id: string;
        page_index: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["RematchGtRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PagePayload"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  update_word_ground_truth_api_projects__project_id__pages__page_index__words__line_index___word_index__gt_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        project_id: string;
        page_index: number;
        line_index: number;
        word_index: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateWordGroundTruthRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PagePayload"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  apply_style_api_projects__project_id__pages__page_index__words__line_index___word_index__style_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        project_id: string;
        page_index: number;
        line_index: number;
        word_index: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ApplyStyleRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PagePayload"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  apply_component_api_projects__project_id__pages__page_index__words__line_index___word_index__component_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        project_id: string;
        page_index: number;
        line_index: number;
        word_index: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ApplyComponentRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PagePayload"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  toggle_validated_api_projects__project_id__pages__page_index__words__line_index___word_index__validated_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        project_id: string;
        page_index: number;
        line_index: number;
        word_index: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ToggleValidatedRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PagePayload"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  validate_batch_api_projects__project_id__pages__page_index__words_validate_batch_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        project_id: string;
        page_index: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ValidateBatchRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PagePayload"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  add_word_api_projects__project_id__pages__page_index__words_add_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        project_id: string;
        page_index: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["AddWordRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PagePayload"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  rebox_word_api_projects__project_id__pages__page_index__words__line_index___word_index__rebox_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        project_id: string;
        page_index: number;
        line_index: number;
        word_index: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ReboxWordRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PagePayload"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  nudge_bbox_api_projects__project_id__pages__page_index__words__line_index___word_index__nudge_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        project_id: string;
        page_index: number;
        line_index: number;
        word_index: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["NudgeBboxRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PagePayload"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  split_word_api_projects__project_id__pages__page_index__words__line_index___word_index__split_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        project_id: string;
        page_index: number;
        line_index: number;
        word_index: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["SplitWordRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PagePayload"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  merge_words_api_projects__project_id__pages__page_index__words__line_index___word_index__merge_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        project_id: string;
        page_index: number;
        line_index: number;
        word_index: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["MergeWordsRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PagePayload"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  erase_pixels_api_projects__project_id__pages__page_index__words__line_index___word_index__erase_pixels_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        project_id: string;
        page_index: number;
        line_index: number;
        word_index: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ErasePixelsRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PagePayload"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  copy_line_gt_api_projects__project_id__pages__page_index__lines__line_index__copy_gt_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        project_id: string;
        page_index: number;
        line_index: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CopyLineGtRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PagePayload"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  delete_scope_api_projects__project_id__pages__page_index__delete_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        project_id: string;
        page_index: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["DeleteScopeRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PagePayload"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  merge_scope_api_projects__project_id__pages__page_index__merge_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        project_id: string;
        page_index: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["MergeScopeRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PagePayload"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  split_paragraph_after_line_api_projects__project_id__pages__page_index__paragraphs__paragraph_index__split_after_line_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        project_id: string;
        page_index: number;
        paragraph_index: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["SplitParagraphAfterLineRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PagePayload"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  split_line_after_word_api_projects__project_id__pages__page_index__lines__line_index__split_after_word_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        project_id: string;
        page_index: number;
        line_index: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["SplitLineAfterWordRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PagePayload"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  split_line_with_selected_words_api_projects__project_id__pages__page_index__lines__line_index__split_with_selected_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        project_id: string;
        page_index: number;
        line_index: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["SplitLineWithSelectedWordsRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PagePayload"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  group_selected_words_into_new_paragraph_api_projects__project_id__pages__page_index__words_group_into_paragraph_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        project_id: string;
        page_index: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["GroupSelectedWordsIntoNewParagraphRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PagePayload"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  refine_scope_api_projects__project_id__pages__page_index__refine_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        project_id: string;
        page_index: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["RefineScopeRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PagePayload"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  start_export_api_projects__project_id__export_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        project_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ExportRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ExportResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  list_jobs_api_jobs_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Job"][];
        };
      };
    };
  };
  get_job_api_jobs__job_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        job_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Job"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_ocr_config_api_ocr_config_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["GetOCRConfigResponse"];
        };
      };
    };
  };
  post_ocr_config_models_api_ocr_config_models_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["SetOCRModelsRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["GetOCRConfigResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  post_ocr_config_rescan_api_ocr_config_rescan_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["GetOCRConfigResponse"];
        };
      };
    };
  };
}
